import { MarketingPageShell } from "@/components/marketing/marketing-page-shell";

export const metadata = { title: "Terms of Service — Schoolum" };

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="space-y-3">
      <h2 className="text-lg font-semibold text-foreground">{title}</h2>
      <div className="space-y-3 text-sm leading-relaxed text-muted">{children}</div>
    </section>
  );
}

export default function TermsPage() {
  return (
    <MarketingPageShell eyebrow="Legal" title="Terms of Service" description="Last updated September 2026">
      <div className="space-y-8 rounded-lg border border-border bg-surface p-6 sm:p-8">
        <Section title="1. Agreement to these terms">
          <p>
            These terms govern access to and use of the Schoolum platform (&quot;the Service&quot;) by a school and its
            authorized staff, students and parents (together, &quot;you&quot; or &quot;your school&quot;). By creating an
            account or using the Service, you agree to these terms.
          </p>
        </Section>

        <Section title="2. Accounts and roles">
          <p>
            A school&apos;s administrators are responsible for the accuracy of the information they enter and for who they
            grant access to within their school. Each account should be used only by the person or role it was created for.
          </p>
        </Section>

        <Section title="3. Subscriptions, trials and billing">
          <p>
            New schools receive a 14-day free trial with full Professional-tier access. After the trial, continued access
            requires an active paid subscription on one of the plans described on our Pricing page. Plan changes take effect
            immediately; a downgrade that would exceed the new plan&apos;s limits (such as active student count) is not
            permitted until resolved.
          </p>
        </Section>

        <Section title="4. Acceptable use">
          <p>You agree not to use the Service to:</p>
          <ul className="list-disc space-y-1.5 pl-5">
            <li>Access or attempt to access another school&apos;s data.</li>
            <li>Circumvent exam security controls, including during a Computer-Based Testing (CBT) attempt.</li>
            <li>Upload unlawful, abusive, or infringing content.</li>
            <li>Interfere with the normal operation or security of the Service.</li>
          </ul>
        </Section>

        <Section title="5. Your school's data">
          <p>
            Your school retains ownership of the data it enters into the Service. We process it only to provide the Service,
            as described in our Privacy Policy. You are responsible for having the appropriate rights and consents to submit
            student and staff data to the platform.
          </p>
        </Section>

        <Section title="6. AI-assisted features">
          <p>
            Where enabled, AI-assisted features (such as AI-generated exam questions or grading suggestions) are advisory
            only. Nothing generated by AI becomes part of an official record — a question, a grade, or a report comment —
            until a human reviewer explicitly approves it.
          </p>
        </Section>

        <Section title="7. Service availability">
          <p>
            We aim to keep the Service available and reliable, but do not guarantee uninterrupted access. We may perform
            maintenance, and will aim to minimize disruption when we do.
          </p>
        </Section>

        <Section title="8. Termination">
          <p>
            A school may cancel its subscription at any time from its billing settings. We may suspend or terminate access
            for a violation of these terms, including a serious or repeated breach of the acceptable use section above.
          </p>
        </Section>

        <Section title="9. Changes to these terms">
          <p>
            We may update these terms from time to time. Material changes will be reflected by updating the date at the top
            of this page.
          </p>
        </Section>

        <Section title="10. Contact us">
          <p>Questions about these terms can be sent through our Contact page.</p>
        </Section>
      </div>
    </MarketingPageShell>
  );
}
