import PDFDocument from "pdfkit";
import { formatCurrency, formatDate } from "@/lib/utils";
import type { Prisma } from "@/generated/prisma/client";

type InvoiceWithRelations = Prisma.InvoiceGetPayload<{
  include: { reservation: { include: { room: true; roomType: true } }; hotel: true };
}>;

interface LineItem {
  description: string;
  quantity: number;
  unitPrice: number;
  total: number;
}

/**
 * Renders a professional A4 PDF invoice for a hotel stay from an already-
 * issued Invoice row (its lineItems JSON snapshot, not a live recompute).
 */
export async function renderInvoicePdf(invoice: InvoiceWithRelations, guestName: string): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: "A4", margin: 50 });
    const chunks: Buffer[] = [];
    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const hotel = invoice.hotel;
    const currency = hotel.currency;
    const reservation = invoice.reservation;
    const lineItems = invoice.lineItems as unknown as LineItem[];

    // Header
    doc.fontSize(18).font("Helvetica-Bold").text(hotel.name, 50, 50);
    doc.fontSize(9).font("Helvetica").fillColor("#555");
    const addressLines = [hotel.address, [hotel.city, hotel.state].filter(Boolean).join(", "), hotel.country, hotel.phone, hotel.email].filter(Boolean);
    doc.text(addressLines.join("\n"), 50, 72);

    doc.fillColor("#000").fontSize(20).font("Helvetica-Bold").text("INVOICE", 350, 50, { width: 200, align: "right" });
    doc.fontSize(10).font("Helvetica").text(`Invoice #: ${invoice.invoiceNumber}`, 350, 78, { width: 200, align: "right" });
    doc.text(`Date: ${formatDate(invoice.issuedAt)}`, 350, 92, { width: 200, align: "right" });
    doc.text(`Reservation: ${reservation.reference}`, 350, 106, { width: 200, align: "right" });

    doc.moveTo(50, 140).lineTo(545, 140).strokeColor("#ddd").stroke();

    // Bill to / stay details
    doc.fillColor("#000").fontSize(11).font("Helvetica-Bold").text("Billed To", 50, 155);
    doc.fontSize(10).font("Helvetica").text(guestName, 50, 172);

    doc.fontSize(11).font("Helvetica-Bold").text("Stay Details", 320, 155);
    doc.fontSize(10).font("Helvetica");
    doc.text(`Room: ${reservation.room.roomNumber} (${reservation.roomType.name})`, 320, 172);
    doc.text(`Check-in: ${formatDate(reservation.checkInDate)}`, 320, 187);
    doc.text(`Check-out: ${formatDate(reservation.checkOutDate)}`, 320, 202);
    doc.text(`Nights: ${reservation.nights}`, 320, 217);

    // Line items table
    let y = 250;
    doc.moveTo(50, y).lineTo(545, y).strokeColor("#ddd").stroke();
    y += 8;
    doc.fontSize(10).font("Helvetica-Bold");
    doc.text("Description", 50, y);
    doc.text("Qty", 350, y, { width: 40, align: "right" });
    doc.text("Unit Price", 390, y, { width: 75, align: "right" });
    doc.text("Total", 470, y, { width: 75, align: "right" });
    y += 16;
    doc.moveTo(50, y).lineTo(545, y).strokeColor("#ddd").stroke();
    y += 8;

    doc.font("Helvetica").fontSize(10);
    for (const item of lineItems) {
      const rowHeight = doc.heightOfString(item.description, { width: 290 }) + 6;
      doc.text(item.description, 50, y, { width: 290 });
      doc.text(String(item.quantity), 350, y, { width: 40, align: "right" });
      doc.text(formatCurrency(item.unitPrice, currency), 390, y, { width: 75, align: "right" });
      doc.text(formatCurrency(item.total, currency), 470, y, { width: 75, align: "right" });
      y += Math.max(rowHeight, 18);
      if (y > 680) {
        doc.addPage();
        y = 50;
      }
    }

    y += 10;
    doc.moveTo(320, y).lineTo(545, y).strokeColor("#ddd").stroke();
    y += 10;

    const summaryRow = (label: string, value: string, bold = false) => {
      doc.font(bold ? "Helvetica-Bold" : "Helvetica").fontSize(bold ? 11 : 10);
      doc.text(label, 320, y, { width: 130 });
      doc.text(value, 470, y, { width: 75, align: "right" });
      y += bold ? 20 : 16;
    };

    summaryRow("Subtotal", formatCurrency(invoice.subtotal, currency));
    if (Number(invoice.discount) > 0) summaryRow("Discount", `-${formatCurrency(invoice.discount, currency)}`);
    if (Number(invoice.tax) > 0) summaryRow("Tax", formatCurrency(invoice.tax, currency));
    summaryRow("Total", formatCurrency(invoice.total, currency), true);
    summaryRow("Amount Paid", formatCurrency(invoice.amountPaid, currency));
    summaryRow(Number(invoice.balance) > 0 ? "Balance Due" : "Balance", formatCurrency(invoice.balance, currency), true);

    doc.fontSize(8).fillColor("#888").text(`Generated by StayOS for ${hotel.name}. Thank you for your stay.`, 50, 780, { width: 495, align: "center" });

    doc.end();
  });
}
