import "server-only";
import { getAiProvider } from "@/lib/ai/providers/registry";
import { requireFeature } from "@/lib/billing/entitlements";
import { logAudit } from "@/lib/audit";
import { prisma } from "@/lib/db";

// ---------------------------------------------------------------------
// Brief section 13/24: AI is never responsible for the deterministic
// notifications themselves (those are all generated by
// notification-rules.ts regardless of whether AI is configured) — this is
// strictly an optional, on-demand "convert my current notifications into
// a readable summary" layer on top, modeled on school-health/ai-insight.ts
// and performance/ai-summary.ts's shared shape: one-shot call, fed only
// already-visible aggregate data (never a new PII exposure — every title
// sent here is already something this exact user can already see in their
// own bell), strict JSON response, validated before use. Deliberately
// never called automatically by the rule engine's background scan (brief
// section 37: "do not overuse AI... never call an AI model for every
// notification") — only when a user explicitly asks for it, so it never
// adds latency or cost to the lazy rule scan every page load triggers.
// ---------------------------------------------------------------------

export function isNotificationAiConfigured(): boolean {
  return getAiProvider() !== null;
}

const SYSTEM_PROMPT = `You write a short, friendly "what needs your attention today" summary for a school-management \
app user, using ONLY the structured list of their own current notifications you are given — never invent a fact, \
number, name, or notification not in the input. Respond with ONLY a JSON object of the shape {"summary": string, \
"topPriorities": string[]} — no prose outside the JSON, no markdown fences. "summary" is 1-3 plain sentences giving \
an overview (e.g. "You have 3 things that need attention today, mostly related to assignments and fees."). \
"topPriorities" is 0-5 short, specific bullet points, ordered most urgent first, each derived directly from one or \
more of the given notifications — never invent an action not implied by the input. Keep language warm, concise, \
and professional. Never mention any individual student, parent, or staff member by name unless their name already \
appears verbatim in a given notification title.`;

export interface NotificationsAiSummary {
  summary: string;
  topPriorities: string[];
}

function parseJsonResponse(text: string): unknown {
  const fenced = text.match(/```(?:json)?\s*([\s\S]*?)```/);
  const raw = fenced ? fenced[1] : text;
  try {
    return JSON.parse(raw.trim());
  } catch {
    throw new Error("The AI response wasn't valid JSON. Try again.");
  }
}

function validateSummary(value: unknown): NotificationsAiSummary {
  if (!value || typeof value !== "object") throw new Error("Unexpected AI response shape.");
  const v = value as Record<string, unknown>;
  const summary = typeof v.summary === "string" ? v.summary.trim() : "";
  if (!summary) throw new Error("The AI response was missing a summary.");
  const topPriorities = Array.isArray(v.topPriorities)
    ? v.topPriorities.filter((s): s is string => typeof s === "string" && s.trim().length > 0).slice(0, 5)
    : [];
  return { summary, topPriorities };
}

/// Reads only this exact user's own unread notifications (the same rows
/// they already see in their bell/notifications page — never a
/// school-wide query, never another user's data) and asks the AI to turn
/// them into one short summary. Returns null (never throws) when there's
/// nothing worth summarizing, so the caller can skip the AI call entirely
/// — brief section 24: "only sent if there's something meaningful to
/// report", applied here to avoid spending an AI call on an empty inbox.
export async function generateNotificationsAiSummary(schoolId: string, userId: string): Promise<NotificationsAiSummary | null> {
  await requireFeature(schoolId, "ai_school_insights");
  const provider = getAiProvider();
  if (!provider) throw new Error("AI notification summaries aren't configured for this deployment.");

  const notifications = await prisma.notification.findMany({
    where: { schoolId, userId, readAt: null, OR: [{ expiresAt: null }, { expiresAt: { gt: new Date() } }] },
    orderBy: [{ priority: "asc" }, { createdAt: "desc" }],
    take: 20,
    select: { title: true, body: true, category: true, priority: true },
  });
  if (notifications.length === 0) return null;

  const payload = {
    notifications: notifications.map((n) => ({ title: n.title, detail: n.body, category: n.category, priority: n.priority })),
  };

  const result = await provider.generate({ systemPrompt: SYSTEM_PROMPT, messages: [{ role: "user", content: JSON.stringify(payload) }], tools: [] });
  if (result.type !== "text") throw new Error("Unexpected AI response format.");

  const summary = validateSummary(parseJsonResponse(result.text));

  await logAudit({
    schoolId,
    userId,
    action: "ai.notifications_summary_generated",
    resourceType: "User",
    resourceId: userId,
    newValue: { notificationCount: notifications.length },
  });

  return summary;
}
